name: Build on Tag

on:
  push:
   tags:
    - '*'
   branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      with:
        arch: arm64
        compiler: clang/14
        defconfig: RM6785_defconfig
        image: Image.gz-dtb

    - name: Release build
      
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: 4.14.319-KernelSU
        artifacts: /github/workspace/zipper/android_kernel_realme_mt6785*
        token: ${{ secrets.GITHUB_TOKEN }}
        
  
    - name: Artifacts
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: 4.14.319-KernelSU
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
       name: release.zip
    # A file, directory or wildcard pattern that describes what to upload
       path: |
        ${{ github.workspace }}/*.zip
        ${{ github.workspace }}/*.gz-dtb
        ${{ github.workspace }}/Image*
        if-no-files-found:
         warn: Output a warning but do not fail the action
