name: Build on Tag

on:
  push:
   tags:
    - '*'
   branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: LOS20-KernelSU
      with:
        arch: arm64
        compiler: clang/14
        defconfig: RM6785_defconfig
        image: Image.gz-dtb

    - name: Release build
      
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: 4.14.319-KernelSU
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
