name: Build on Tag

on:
  push:
   tags:
    - '*'
   branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      with:
        arch: arm64
        compiler: clang/14
        defconfig: RM6785_defconfig
        image: Image.gz-dtb

    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      with:
        gh-cli-version: 2.14.2 # optional, see action.yml for current default
      
    - name: Release build
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}    
      run: |
        pwd
        ls -la ./out
        git config --global --add safe.directory "/home/runner/work/android_kernel_realme_mt6785/android_kernel_realme_mt6785"        
        export RELEASE_NAME="4.14.319-KernelSU"
        export RELEASE_TITLE="4.14.319-KernelSU"
        export RELEASE=$RELEASE_NAME
        export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        find /home/runner/work/android_kernel_realme_mt6785/android_kernel_realme_mt6785 -type f -name "*.zip" > deb
        export DEB=$(cat deb)
        echo $DEB
        echo $RELEASE
        echo $RELEASE_TITLE
        echo $RELEASE_NAME
        gh release create --title $RELEASE_TITLE --generate-notes -R https://github.com/gustavokch/android_kernel_realme_mt6785 $RELEASE_NAME $DEB
  
    - name: Artifacts
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      uses: ncipollo/release-action@v1
      with:
        tag: 4.14.319-KernelSU-release
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
