name: Build on Tag

on:
  push:
   tags:
    - '*'
   branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      with:
        arch: arm64
        compiler: clang/14
        defconfig: RM6785_defconfig
        image: Image.gz-dtb

    - name: Release build
      
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
        sudo apt install debhelper zip -y
        git config --global --add safe.directory "/__w//android_kernel_realme_mt6785/android_kernel_realme_mt6785"
	      export TAG="KernelSU"

	      export NAME=$(($RELEASE_START+$TAG))
        export RELEASE_NAME=$(($RELEASE_START+$TAG))
        export RELEASE_TITLE=$(($RELEASE_START+$TAG+$GITHUB_RUN_NUMBER))
        export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        find / -type f -name "*.zip" > deb
        export DEB=$(cat deb)
        zip ../$RELEASE_NAME.zip -@ < deb
        echo $RELEASE
        echo $RELEASE_TITLE
        echo $RELEASE_NAME
        gh release create --title $RELEASE_TITLE --generate-notes -R https://github.com/gustavokch/linux-mainline-kernel $RELEASE $DEB
